# Generated by Django 5.2.1 on 2025-05-26 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('business_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route_url', models.URLField()),
                ('forward_description', models.TextField(blank=True, null=True)),
                ('return_description', models.TextField(blank=True, null=True)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_end', to='Nodes.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_start', to='Nodes.node')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Routes.transportcompany')),
            ],
        ),
        migrations.CreateModel(
            name='RouteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nodes.edge')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Routes.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
