# Generated by Django 5.2.1 on 2025-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='route',
            table='routes',
        ),
        migrations.AlterModelTable(
            name='routeedge',
            table='route_edges',
        ),
        migrations.AlterModelTable(
            name='transportcompany',
            table='transport_companies',
        ),
    ]
