# Generated by Django 5.2.1 on 2025-06-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0003_alter_edge_table_alter_node_table'),
        ('Routes', '0002_alter_route_table_alter_routeedge_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeedge',
            name='direction',
            field=models.CharField(choices=[('I', 'Ida'), ('V', 'Vuelta')], default='I', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('direction', models.CharField(choices=[('I', 'Ida'), ('V', 'Vuelta')], max_length=1)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nodes.node')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Routes.route')),
            ],
            options={
                'db_table': 'route_nodes',
                'ordering': ['order'],
            },
        ),
    ]
