# Generated by Django 5.2.1 on 2025-05-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0002_node_osm_id_alter_node_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='edge',
            table='edges',
        ),
        migrations.AlterModelTable(
            name='node',
            table='nodes',
        ),
    ]
